### PR TITLE
Fix API endpoints conferences/id/rooms/ & tracks/ issue

### LINKED ISSUE #874: API endpoints /api/v1/conferences/shorttitle/rooms/  and tracks/  fails with error
Steps to reproduce:
1. Create a conference,say testconf (short title)
2. Add a track
3. Add a venue and few rooms to that venue

Now  go to /api/v1/conferences/testconf/rooms/
It raises  error: undefined method `venue' for nil:NilClass

Similarly try /api/v1/conferences/testconf/tracks
it raises error: undefined method `tracks'

### PR DESCRIPTION
**Pull request by nishanthvijayan**
Fixes #874

### CODE REVIEW

**Comment by differentreality** [comment]
Yeap that looks good! Shall we test it?

**Comment by nishanthvijayan** [comment]
Sure.I'll start right away.

**Comment by nishanthvijayan** [comment]
@differentreality  Done.

File: app/controllers/api/v1/rooms_controller.rb [hunk 1]
```diff
@@ -8,8 +8,7 @@ def index
         if params[:conference_id].blank?
```
Comment (differentreality) [inline app/controllers/api/v1/rooms_controller.rb]: Actually this can just be `if @conference` and invert the code of if/else.

File: spec/requests/api/v1/tracks_spec.rb [hunk 2]
```diff
@@ -0,0 +1,39 @@
+require 'spec_helper'
+
+describe 'API tracks' do
+  let!(:conference) { create(:conference) }
+  let!(:track1) { create(:track, program_id: conference.program.id) }
```
Comment (differentreality) [inline spec/requests/api/v1/tracks_spec.rb]: This track is supposed to have the name 'Example Track', but to check that I would have to go back to the factory. You can set the name of the track here and call it 'Conference Track' or something like that, so that you can also lose the comment on line 34. The name of the variable can also be something like track_of_conference instead of track1, so that it makes more sense.

**Comment by nishanthvijayan** [comment]
@differentreality  I've cleaned up the tests.

**Comment by differentreality** [comment]
@hennevogel do we need to keep the API tests in spec/requests instead of spec/controllers?

**Comment by hennevogel** [comment]
No. `spec/requests` is for [request specs](https://relishapp.com/rspec/rspec-rails/docs/request-specs/request-spec). These are controller tests.

File: app/controllers/api/v1/rooms_controller.rb [hunk 3]
```diff
@@ -5,11 +5,10 @@ class RoomsController < Api::BaseController
       respond_to :json
 
       def index
-        if params[:conference_id].blank?
-          rooms = Room.all
+        if @conference
+          @conference.venue ? (rooms = @conference.venue.rooms) : (rooms = [])
```
Comment (ChrisBr) [inline app/controllers/api/v1/rooms_controller.rb]: please don't assign variables in conditionals. This is really hard to read! Instead do sth like:

``
rooms = @conference.venue ? ...
``

Furthermore please don't return an empty Array, instead use ``Room.none`` to stick to the ActiveRecord API.

Long answer, short: Please change the line to:

```
rooms = @conference.venue ? @conference.venue.rooms : Room.none
```

File: app/controllers/api/v1/tracks_controller.rb [hunk 4]
```diff
@@ -5,7 +5,7 @@ class TracksController < Api::BaseController
       respond_to :json
 
       def index
-        @conference ? (tracks = @conference.tracks) : (tracks = Track.all)
+        @conference ? (tracks = @conference.program.tracks) : (tracks = Track.all)
```
Comment (ChrisBr) [inline app/controllers/api/v1/tracks_controller.rb]: Same here: Please don't assign variables in a conditional statement!

Comment (nishanthvijayan) [inline app/controllers/api/v1/tracks_controller.rb]: OK.It was already in that form.So I assumed it was okay.I'll fix everything ASAP

File: app/controllers/api/v1/rooms_controller.rb (hunk 3 above)
Comment (nishanthvijayan) [inline app/controllers/api/v1/rooms_controller.rb]: Changing it as you suggested would lead to a rubocop offence 
[Style/ConditionalAssignment: Use the return of the conditional for variable assignment and comparison](http://www.rubydoc.info/github/bbatsov/RuboCop/RuboCop/Cop/Style/ConditionalAssignment)
How about this?
```
rooms = if @conference
      @conference.venue ? @conference.venue.rooms : Room.none
    else
      Room.all
    end
```

Comment (ChrisBr) [inline app/controllers/api/v1/rooms_controller.rb]: Hm, I don't like the rubocop suggestions ...
Do we need the rooms variable at all?

What about?
```
if @conference
  respond_with @conference.venue ? @conference.venue.rooms : Room.none
else
  respond_with Room.all
end

(note that this is untested...)
```

File: app/controllers/api/v1/tracks_controller.rb (hunk 4 above)
Comment (ChrisBr) [inline app/controllers/api/v1/tracks_controller.rb]: Okay! Ever heard from the [boyscout rule](http://programmer.97things.oreilly.com/wiki/index.php/The_Boy_Scout_Rule)? ;)

File: app/controllers/api/v1/rooms_controller.rb (hunk 3 above)
Comment (nishanthvijayan) [inline app/controllers/api/v1/rooms_controller.rb]: Yup that works.

File: app/controllers/api/v1/tracks_controller.rb (hunk 4 above)
Comment (nishanthvijayan) [inline app/controllers/api/v1/tracks_controller.rb]: Sorry my bad.

**Comment by ChrisBr** [comment]
@nishanthvijayan cool :+1: Good work!
