### PR TITLE
Fixed paper trail inconsistent results for numeric values.

### LINKED ISSUE #1307: Paper_Trail Issue
There is a known issue in paper_trail that whenever we Query the 'versions.object' column (or 'object_changes' column), like this:

> PaperTrail::Version.where_object(attr1: val1, attr2: val2)
> PaperTrail::Version.where_object_changes(attr1: val1)

it evaluates inconsistent results for numeric values due to limitations of SQL wildcard matchers against the serialized objects.

we are also doing  like this here:
https://github.com/openSUSE/osem/blob/master/app/controllers/admin/events_controller.rb#L53

To find out more about this issue look at the comments here:
https://github.com/openSUSE/osem/pull/1283#issuecomment-280310475

### PR DESCRIPTION
**Pull request by siddhantbajaj**
There is a known issue in paper_trail that whenever we Query the 'versions.object' column (or 'object_changes' column), like this:

```
PaperTrail::Version.where_object(attr1: val1, attr2: val2)
PaperTrail::Version.where_object_changes(attr1: val1)
```
it evaluates inconsistent results for numeric values due to limitations of SQL wildcard matchers against the serialized objects.

So to fix this issue I have manually formed the where query instead of using where_object and where_object_changes. I have also added test for the same.

To recreate this issue you can create 2 events like this:
`Event_without_commercial{id:1}, Event_with_commercial{id:2}`
a event commercial:
`event_commercial{id:1, event_id:2}`
version for this commercial will be like:
`Version{object_change: "...id:1...commercialable_id:2"}`
**So this version will be shown in the history of both the events.**  

closes #1307

### CODE REVIEW

File: app/controllers/admin/events_controller.rb [hunk 1]
```diff
@@ -50,8 +50,8 @@ def show
       @ratings = @event.votes.includes(:user)
       @difficulty_levels = @program.difficulty_levels
       @versions = @event.versions |
-       PaperTrail::Version.where(item_type: 'Commercial').where_object(commercialable_id: @event.id, commercialable_type: 'Event') |
-       PaperTrail::Version.where(item_type: 'Commercial').where_object_changes(commercialable_id: @event.id, commercialable_type: 'Event') |
+       PaperTrail::Version.where(item_type: 'Commercial').where('object LIKE ?', "%commercialable_id: #{@event.id}\ncommercialable_type: Event%") |
```
Comment (ChrisBr) [inline app/controllers/admin/events_controller.rb]: Why do we need the line break here?

Comment (siddhantbajaj) [inline app/controllers/admin/events_controller.rb]: Because that is how paper trail stores object. Something like this :

>"---\nid: 5\ncommercial_id: \ncommercial_type: \ncommercialable_id : 8\ncommercialable_type: Event\ncreated_at: 2017-03-06 19:40:15.067701000 Z\nupdated_at: 2017-03-06 19:40:15.067701000 Z\nurl: https://www.youtube.com/watch?v="

**Comment by differentreality** [comment]
Please rewrite your PR and commit title, saying what this is doing.

@ChrisBr do you need anything else here?

**Comment by siddhantbajaj** [comment]
@differentreality I have made the changes. :+1:

**Comment by differentreality** [comment]
Can we add tests to make sure this is now fixed?

**Comment by siddhantbajaj** [comment]
@differentreality added tests. :+1:

**Comment by differentreality** [comment]
@siddhantbajaj yeap, I saw :) (I get an email when a commit is pushed in any PR of OSEM). You haven't fixed failures in Travis though...

**Comment by differentreality** [comment]
I would expect a controller test making sure @versions variable is assigned the correct value.
The concept is that you will write tests that would fail on our master, but pass in your branch with the changes you implemented.

**Comment by siddhantbajaj** [comment]
@differentreality okay but isn't this test doing the same thing. It will fail in master branch. Since before every test we clear the database. So the 2 events created in this test will be something like this:
Event_without_commercial{id:1}, Event_with_commercial{id:2} and the event_commercial{id:1, event_id:2}
and version for this commercial will be like Version{object_change: "...id:1...commercialable_id:2"}. So this version will be shown in the history of both the events and the test would fail.

**Comment by differentreality** [comment]
Are you saying that the feature test is failing if you run it on master?

**Comment by siddhantbajaj** [comment]
Yes.

**Comment by siddhantbajaj** [comment]
Sorry just realised test was passing in the master branch because i was creating Event_with_commercial first so it was getting id=1 but I wanted Event_without_commercial to get id=1. Fixed this now this test would fail on master.

**Comment by differentreality** [comment]
OK nice :-)
I would still add the controller test.

**Comment by differentreality** [comment]
@siddhantbajaj ping

**Comment by siddhantbajaj** [comment]
Okay I will add controller test as well. :+1:

File: spec/controllers/admin/events_controller_spec.rb [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+  let!(:event_with_commercial) { create(:event, program: conference.program) }
+  let!(:event_commercial) { create(:event_commercial, commercialable: event_with_commercial, url: 'https://www.youtube.com/watch?v=M9bq_alk-sw') }
+  with_versioning do
+    context 'logged in as an organizer' do
+      before :each do
+        sign_in(organizer)
+      end
+
+      describe 'GET #show' do
+        let(:show_action){ get :show, id: event_without_commercial.id, conference_id: conference.short_title }
```
Comment (differentreality) [inline spec/controllers/admin/events_controller_spec.rb]: This should go in a `before :each`

File: spec/controllers/admin/events_controller_spec.rb [hunk 3]
```diff
@@ -0,0 +1,26 @@
...
+        it 'assigns versions' do
+          show_action
+          versions = assigns(:versions) - event_without_commercial.versions
+          expect(versions).to match_array([])
```
Comment (differentreality) [inline spec/controllers/admin/events_controller_spec.rb]: Here I'd expect to see:

`expect(assigns(:versions).to ....`

File: spec/controllers/admin/events_controller_spec.rb (hunk 2 above)
Comment (siddhantbajaj) [inline spec/controllers/admin/events_controller_spec.rb]: I don't think we can use let inside before block.

File: spec/controllers/admin/events_controller_spec.rb (hunk 3 above)
Comment (siddhantbajaj) [inline spec/controllers/admin/events_controller_spec.rb]: done.

File: spec/controllers/admin/events_controller_spec.rb (hunk 2 above)
Comment (differentreality) [inline spec/controllers/admin/events_controller_spec.rb]: Sorry, that's my point, don't use let. Look at other controller tests to see how it is done there ;)

Comment (siddhantbajaj) [inline spec/controllers/admin/events_controller_spec.rb]: Actually I was not going going to use let first but then I looked at other controller tests and its done the same way like this. Here it is:
https://github.com/openSUSE/osem/blob/master/spec/controllers/admin/schedules_controller_spec.rb#L37

Comment (differentreality) [inline spec/controllers/admin/events_controller_spec.rb]: Go with this
https://github.com/openSUSE/osem/blob/master/spec/controllers/admin/roles_controller_spec.rb#L16

Comment (siddhantbajaj) [inline spec/controllers/admin/events_controller_spec.rb]: done :-)

File: spec/features/versions_spec.rb [hunk 4]
```diff
@@ -270,6 +270,20 @@
     expect(page).to have_text("Someone (probably via the console) deleted commercial in event #{event.title} in conference #{conference.short_title}")
   end
 
+  scenario 'display changes in event commercials in event history', feature: true, versioning: true, js: true do
+    event__without_commercial = create(:event, program: conference.program)
```
Comment (differentreality) [inline spec/features/versions_spec.rb]: single underscore

File: spec/controllers/admin/events_controller_spec.rb [hunk 5]
```diff
@@ -0,0 +1,22 @@
...
+  let!(:event_without_commercial) { create(:event, program: conference.program) }
+  let!(:event_with_commercial) { create(:event, program: conference.program) }
+  let!(:event_commercial) { create(:event_commercial, commercialable: event_with_commercial, url: 'https://www.youtube.com/watch?v=M9bq_alk-sw') }
+  with_versioning do
+    describe 'GET #show' do
+      before :each do
+        sign_in(organizer)
+        get :show, id: event_without_commercial.id, conference_id: conference.short_title
+      end
+      it 'assigns versions' do
```
Comment (Ana06) [inline spec/controllers/admin/events_controller_spec.rb]: please leave an empty line before this `it`

File: spec/controllers/admin/events_controller_spec.rb [hunk 6]
```diff
@@ -0,0 +1,22 @@
+require 'spec_helper'
+
+describe Admin::EventsController do
+  let!(:conference) { create(:conference) }
+  let!(:organizer_role) { Role.find_by(name: 'organizer', resource: conference) }
+  let!(:organizer) { create(:user, role_ids: organizer_role.id) }
+  let!(:event_without_commercial) { create(:event, program: conference.program) }
+  let!(:event_with_commercial) { create(:event, program: conference.program) }
+  let!(:event_commercial) { create(:event_commercial, commercialable: event_with_commercial, url: 'https://www.youtube.com/watch?v=M9bq_alk-sw') }
+  with_versioning do
```
Comment (Ana06) [inline spec/controllers/admin/events_controller_spec.rb]: please leave an empty line before this line

File: spec/controllers/admin/events_controller_spec.rb [hunk 7]
```diff
@@ -0,0 +1,22 @@
+require 'spec_helper'
+
+describe Admin::EventsController do
+  let!(:conference) { create(:conference) }
```
Comment (Ana06) [inline spec/controllers/admin/events_controller_spec.rb]: Can't any of these `let!` be turned into a `let`? using lazy evaluation I mean

File: spec/features/versions_spec.rb [hunk 8]
```diff
@@ -270,6 +270,20 @@
     expect(page).to have_text("Someone (probably via the console) deleted commercial in event #{event.title} in conference #{conference.short_title}")
   end
 
+  scenario 'display changes in event commercials in event history', feature: true, versioning: true, js: true do
+    event_without_commercial = create(:event, program: conference.program)
+    event_with_commercial = create(:event, program: conference.program)
```
Comment (Ana06) [inline spec/features/versions_spec.rb]: event_with_comercial is created several times in this file. It would be nice if we move it to a `let` and reuse it.

File: spec/controllers/admin/events_controller_spec.rb (hunk 7 above)
Comment (siddhantbajaj) [inline spec/controllers/admin/events_controller_spec.rb]: Okay done. :+1:

File: spec/controllers/admin/events_controller_spec.rb (hunk 6 above)
Comment (siddhantbajaj) [inline spec/controllers/admin/events_controller_spec.rb]: :+1:

File: spec/controllers/admin/events_controller_spec.rb (hunk 5 above)
Comment (siddhantbajaj) [inline spec/controllers/admin/events_controller_spec.rb]: :+1:

File: spec/features/versions_spec.rb (hunk 8 above)
Comment (siddhantbajaj) [inline spec/features/versions_spec.rb]: done. :+1:

File: spec/controllers/admin/events_controller_spec.rb [hunk 9]
```diff
@@ -0,0 +1,26 @@
+require 'spec_helper'
+
+describe Admin::EventsController do
+  let(:conference) { create(:conference) }
+  let(:organizer_role) { Role.find_by(name: 'organizer', resource: conference) }
+  let(:organizer) { create(:user, role_ids: organizer_role.id) }
+  let(:event_without_commercial) { create(:event, program: conference.program) }
+  let(:event_with_commercial) { create(:event, program: conference.program) }
```
Comment (differentreality) [inline spec/controllers/admin/events_controller_spec.rb]: This way you are not using this anywhere. Leave it with ! to be created in the beginning.

File: spec/controllers/admin/events_controller_spec.rb [hunk 10]
```diff
@@ -0,0 +1,26 @@
...
+  let(:event_commercial) { create(:event_commercial, commercialable: event_with_commercial, url: 'https://www.youtube.com/watch?v=M9bq_alk-sw') }
+
+  with_versioning do
+    describe 'GET #show' do
+      before :each do
+        sign_in(organizer)
+        event_without_commercial
```
Comment (differentreality) [inline spec/controllers/admin/events_controller_spec.rb]: For the 3 events you want created, don't call them here, I think we are just adding extra code for no reason.

**Comment by differentreality** [comment]
Please add a description to the PR in the first comment, describing what you are doing. Also please rebase (should make the hakiri warning go away).

File: spec/controllers/admin/events_controller_spec.rb (hunk 9 above)
Comment (siddhantbajaj) [inline spec/controllers/admin/events_controller_spec.rb]: :+1:

File: spec/controllers/admin/events_controller_spec.rb (hunk 10 above)
Comment (siddhantbajaj) [inline spec/controllers/admin/events_controller_spec.rb]: :+1:

**Comment by siddhantbajaj** [comment]
done. :+1:

**Comment by differentreality** [comment]
@siddhantbajaj can you elaborate on your description in which cases the error occurs? How could one recreate this? Based on that, I want to double check our test is accurate.

**Comment by siddhantbajaj** [comment]
done. :+1:

**Comment by differentreality** [comment]
Nice @siddhantbajaj I am wondering if our test should double check this for future reference. 
If I am not mistaken, according to https://github.com/openSUSE/osem/pull/1283#issuecomment-280310475 that would be that the `commercial.id` needs to be the same as an `id of Events`, and the `commercial.commercialable_id` should be `different` than the id.

**Comment by differentreality** [comment]
OK let's get this in, @siddhantbajaj please squash! Good work!

**Comment by siddhantbajaj** [comment]
done. :+1:

**Comment by Ana06** [comment]
@siddhantbajaj There are some Rubocop/haml-lint failures but they seems to be unrelated to this PR. I'll open a PR because otherwise everything will start failing.

**Comment by differentreality** [comment]
@Ana06 #1483?

**Comment by Ana06** [comment]
@differentreality #1483 fix Rubocop, but not haml-lint

**Comment by Ana06** [comment]
@differentreality I guess we can merge this anyway, as the failures are unrelated, right?

**Comment by differentreality** [comment]
:+1:
