### PR TITLE
Fixed DeleteEventSchedules issue

### LINKED ISSUE #1333: Issue with DeleteEventSchedules method
I was playing around with conference start and end hour attribute when I found some issues related to DeleteEventSchedules method in conference controller. This method basically delete all EventSchedules that are not in the hours range of that particular conference. Issues that I found:
1. It deletes EventSchedules of all the conferences that are not in the hours range. Instead it should  delete EventSchedules of those events only that belong to that particular conference only.
2. If we set invalid start or end hour attribute of a conference then also EventSchedules gets deleted even though conference is not successfully updated.

For more information on DeleteEventSchedules method:
https://github.com/openSUSE/osem/pull/1143

### PR DESCRIPTION
**Pull request by siddhantbajaj**
closes #1333

### CODE REVIEW

File: app/controllers/admin/conferences_controller.rb [hunk 1]
```diff
@@ -82,7 +82,9 @@ def update
       short_title = @conference.short_title
       @conference.assign_attributes(conference_params)
       send_mail_on_conf_update = @conference.notify_on_dates_changed?
-      delete_event_schedules if @conference.start_hour_changed? || @conference.end_hour_changed?
+      if @conference.valid? && (@conference.start_hour_changed? || @conference.end_hour_changed?)
```
Comment (differentreality) [inline app/controllers/admin/conferences_controller.rb]: You can still do that in one line

Comment (siddhantbajaj) [inline app/controllers/admin/conferences_controller.rb]: yes. :+1:

File: app/controllers/admin/conferences_controller.rb [hunk 2]
```diff
@@ -82,7 +82,7 @@ def update
       short_title = @conference.short_title
       @conference.assign_attributes(conference_params)
       send_mail_on_conf_update = @conference.notify_on_dates_changed?
-      delete_event_schedules if @conference.start_hour_changed? || @conference.end_hour_changed?
+      delete_event_schedules if @conference.valid? && (@conference.start_hour_changed? || @conference.end_hour_changed?)
```
Comment (Ana06) [inline app/controllers/admin/conferences_controller.rb]: you could move this inside the

`if @conference.update_attributes(conference_params)`

and then you now the conference is valid and you can just write:

`delete_event_schedules if @conference.start_hour_changed? || @conference.end_hour_changed?`

I like it more as you are sure that the conference start/end time was changed.

Comment (siddhantbajaj) [inline app/controllers/admin/conferences_controller.rb]: Yes I tried that first,but the problem with this approach is:
> @conference.start_hour_changed? || @conference.end_hour_changed?

will not give you true as the conference is now updated.
Then I thought of using previous_changes()  but that too did not give the desired results.

Comment (Ana06) [inline app/controllers/admin/conferences_controller.rb]: what about moving it to a `after_update` callback? You should be able to use `changed?` there and it is much more clear.

**Comment by siddhantbajaj** [comment]
@Ana06 made the changes. :+1:

File: app/models/conference.rb [hunk 3]
```diff
@@ -81,6 +82,21 @@ def user_registered? user
   end
 
   ##
+  # Delete all EventSchedules that are not in the hours range
+  # After the conference has been successfully updated
+  def delete_event_schedules
+    if self.start_hour_changed? || self.end_hour_changed?
+      event_schedules = EventSchedule.select do |e|
```
Comment (lagartoflojo) [inline app/models/conference.rb]: `EventSchedule.select do |e|` will go over EVERY event schedule in the database. Not cool.
We should try to scope this somehow.
Maybe adding a `has_many :event_schedules` to the conference.

Comment (siddhantbajaj) [inline app/models/conference.rb]: > Maybe adding a has_many :event_schedules to the conference.

Yes looks like the ideal solution. But it requires a lot of changes so should it be a part of this PR or should we handle this in a different PR? @Ana06 @lagartoflojo

Comment (Ana06) [inline app/models/conference.rb]: @lagartoflojo I think it would be even cooler if we add a `has_many thought` (using schedules relation for example) relation in program, as it is easier. and with that you can just do here:

`conference.program.event_schedules.select do |event_schedule|`

So, it implies just modifying two lines :wink: Add it in a different commit in this PR please :slightly_smiling_face:

Comment (Ana06) [inline app/models/conference.rb]: And please use `event` instead `e`

Comment (siddhantbajaj) [inline app/models/conference.rb]: @Ana06 `has_many thought` Sorry I didn't understand this. Are you trying to say instead of conference, program should have one-to-many relation with event_schedules model?

Comment (Ana06) [inline app/models/conference.rb]: @siddhantbajaj I mean adding a `has_many thought` relation in program to be able to call it like 

``` Ruby
conference.program.event_schedules.select do |event_schedule|
```

http://guides.rubyonrails.org/association_basics.html#the-has-many-through-association

Comment (siddhantbajaj) [inline app/models/conference.rb]: @Ana06 Okay so by `has_many thought` here you meant `has_many through`.I wasn't getting  what **thought** meant here and  was thinking that you might mean has many through association but then thought of confirming it first. But don't we generally use has many through associations  for many to many relation. Why do you want to use it for one to many relation between program and event schedule? Please correct me if am getting it all wrong.

Comment (Ana06) [inline app/models/conference.rb]: @siddhantbajaj take a look at this paragraph of the [link](http://guides.rubyonrails.org/association_basics.html#the-has-many-through-association), as it exactly our case:


> The has_many :through association is also useful for setting up "shortcuts" through nested has_many associations. For example, if a document has many sections, and a section has many paragraphs, you may sometimes want to get a simple collection of all paragraphs in the document.

Comment (siddhantbajaj) [inline app/models/conference.rb]: Thanks @Ana06 and sorry I didn't knew this thing that's why didn't get it first time. I have made the changes. :wink:

File: app/models/conference.rb [hunk 4]
```diff
@@ -86,11 +86,11 @@ def user_registered? user
   # After the conference has been successfully updated
   def delete_event_schedules
     if self.start_hour_changed? || self.end_hour_changed?
-      event_schedules = EventSchedule.select do |e|
-        e.event.program == program &&
-        (e.start_time.strftime('%H').to_i < start_hour ||
-        e.end_time.strftime('%H').to_i > end_hour ||
-        (e.end_time.strftime('%H').to_i == end_hour && e.end_time.strftime('%M').to_i > 0))
+      event_schedules = program.event_schedules.select do |event_schedule|
+        event_schedule.event.program == program &&
```
Comment (Ana06) [inline app/models/conference.rb]: you don't need that line now, right?

File: app/models/conference.rb [hunk 5]
```diff
@@ -86,11 +86,11 @@ def user_registered? user
...
+        (event_schedule.start_time.strftime('%H').to_i < start_hour ||
```
Comment (Ana06) [inline app/models/conference.rb]: you can use here the `hour` method: :wink: 

`event_schedule.start_time.hour < start_hour`

Comment (siddhantbajaj) [inline app/models/conference.rb]: done.

File: app/models/conference.rb (hunk 4 above)
Comment (siddhantbajaj) [inline app/models/conference.rb]: Yes you are right, :+1:

File: app/models/conference.rb [hunk 6]
```diff
@@ -87,10 +87,9 @@ def user_registered? user
   def delete_event_schedules
     if self.start_hour_changed? || self.end_hour_changed?
       event_schedules = program.event_schedules.select do |event_schedule|
-        event_schedule.event.program == program &&
-        (event_schedule.start_time.strftime('%H').to_i < start_hour ||
-        event_schedule.end_time.strftime('%H').to_i > end_hour ||
-        (event_schedule.end_time.strftime('%H').to_i == end_hour && event_schedule.end_time.strftime('%M').to_i > 0))
+        event_schedule.start_time.hour < start_hour ||
+        event_schedule.end_time.hour > end_hour ||
+        (event_schedule.end_time.hour == end_hour && event_schedule.end_time.hour > 0)
```
Comment (Ana06) [inline app/models/conference.rb]: I think here you meant `minute` instead of `hour` in the second part: 

`(event_schedule.end_time.hour == end_hour && event_schedule.end_time.minute > 0)`

Comment (siddhantbajaj) [inline app/models/conference.rb]: Yes I have made the change.  :+1:

**Comment by siddhantbajaj** [comment]
Okay. :wink:

File: spec/models/conference_spec.rb [hunk 7]
```diff
@@ -1639,4 +1639,27 @@
       expect(free_ticket.price_cents).to eq(0)
     end
   end
+
+  describe 'after_update' do
+    let(:conference) { create(:full_conference) }
```
Comment (Ana06) [inline spec/models/conference_spec.rb]: why do you need it to be a `full conference`?

File: spec/models/conference_spec.rb [hunk 8]
```diff
@@ -1639,4 +1639,27 @@
...
+    let(:first_scheduled_event) { create(:event_scheduled, program: conference.program, hour: conference.start_date + conference.start_hour.hours) }
+    let(:second_scheduled_event) { create(:event_scheduled, program: conference.program, hour: conference.start_date + conference.end_hour.hours + 1.hour) }
+
+    it 'delete event schedules that are not in hour ranges, when conference start hour is updated' do
+      first_scheduled_event
+      conference.start_hour = conference.start_hour + 1.hour
+      conference.save
+      conference.run_callbacks :update
+      free_ticket = conference.tickets.first
```
Comment (Ana06) [inline spec/models/conference_spec.rb]: why do you need this for? :confused:

File: spec/models/conference_spec.rb [hunk 9]
```diff
@@ -1639,4 +1639,27 @@
...
+
+  describe 'after_update' do
+    let(:conference) { create(:full_conference) }
+    let(:first_scheduled_event) { create(:event_scheduled, program: conference.program, hour: conference.start_date + conference.start_hour.hours) }
+    let(:second_scheduled_event) { create(:event_scheduled, program: conference.program, hour: conference.start_date + conference.end_hour.hours + 1.hour) }
+
+    it 'delete event schedules that are not in hour ranges, when conference start hour is updated' do
+      first_scheduled_event
+      conference.start_hour = conference.start_hour + 1.hour
+      conference.save
```
Comment (Ana06) [inline spec/models/conference_spec.rb]: why not just

`expect(conference).not_to be valid?`

Comment (siddhantbajaj) [inline spec/models/conference_spec.rb]: why would conference not be valid? :confused:

File: spec/models/conference_spec.rb (hunk 7 above)
Comment (siddhantbajaj) [inline spec/models/conference_spec.rb]: No specific reason just prefer to use full_conference with all basic things set. But yes conference will do just fine here. :+1:

Comment (siddhantbajaj) [inline spec/models/conference_spec.rb]: No specific reason just prefer to use full_conference with all basic things set. But yes conference will do just fine here. :+1:

File: spec/models/conference_spec.rb (hunk 8 above)
Comment (siddhantbajaj) [inline spec/models/conference_spec.rb]: Sorry my bad, not needed. :confounded:

File: spec/models/conference_spec.rb [hunk 10]
```diff
@@ -1639,4 +1639,26 @@
       expect(free_ticket.price_cents).to eq(0)
     end
   end
+
+  describe 'after_update' do
+    let(:conference) { create(:conference) }
+    let(:first_scheduled_event) { create(:event_scheduled, program: conference.program, hour: conference.start_date + conference.start_hour.hours) }
+    let(:second_scheduled_event) { create(:event_scheduled, program: conference.program, hour: conference.start_date + conference.end_hour.hours + 1.hour) }
```
Comment (differentreality) [inline spec/models/conference_spec.rb]: I think it makes more sense to name the variables into something like scheduled_event_after_conference, scheduled_event_during_conference, etc.

Comment (differentreality) [inline spec/models/conference_spec.rb]: I would also add a scheduled event during the conference, so that we can be testing that we are only deleting the events outside conference hours, and not the other ones.

File: spec/models/conference_spec.rb (hunk 9 above)
Comment (Ana06) [inline spec/models/conference_spec.rb]: oh, sorry. I read it wrong :rofl:

File: spec/models/conference_spec.rb (hunk 7 above)
Comment (Ana06) [inline spec/models/conference_spec.rb]: then there is already a `conference` variable at the top: https://github.com/siddhantbajaj/osem/blob/007804f3ff4d43dd4ac2137d254cc6e1112839c2/spec/models/conference_spec.rb#L7

Although it is call subject, but we should use it here, so we don't have to define it twice. :wink:

File: spec/models/conference_spec.rb [hunk 11]
```diff
@@ -1639,4 +1639,26 @@
...
+
+    it 'delete event schedules that are not in hour ranges, when conference start hour is updated' do
+      first_scheduled_event
+      conference.start_hour = conference.start_hour + 1.hour
+      conference.save
+      conference.run_callbacks :update
```
Comment (Ana06) [inline spec/models/conference_spec.rb]: why do you need this?

File: spec/models/conference_spec.rb [hunk 12]
```diff
@@ -1639,4 +1639,26 @@
...
+      expect(EventSchedule.count).to eq(0)
```
Comment (Ana06) [inline spec/models/conference_spec.rb]: what about using `to_change` instead of to `eq`? Then we know that the EventSchedules where really deleted.

File: spec/models/conference_spec.rb [hunk 13]
```diff
@@ -1639,4 +1639,26 @@
...
+    end
+
+    it 'delete event schedules that are not in hour ranges, when conference end hour is updated' do
+      second_scheduled_event
+      conference.end_hour = conference.end_hour - 2.hours
+      conference.save
+      conference.run_callbacks :update
+      expect(EventSchedule.count).to eq(0)
```
Comment (Ana06) [inline spec/models/conference_spec.rb]: same here, use `to_change` instead of to `eq`, then we know that the EventSchedules where really deleted.

File: spec/models/conference_spec.rb (hunk 10 above)
Comment (siddhantbajaj) [inline spec/models/conference_spec.rb]: :+1:

File: spec/models/conference_spec.rb (hunk 13 above)
Comment (siddhantbajaj) [inline spec/models/conference_spec.rb]: :+1:

File: spec/models/conference_spec.rb (hunk 12 above)
Comment (siddhantbajaj) [inline spec/models/conference_spec.rb]: :+1:

File: spec/models/conference_spec.rb (hunk 11 above)
Comment (siddhantbajaj) [inline spec/models/conference_spec.rb]: I was actually following the pattern given here:
https://github.com/siddhantbajaj/osem/blob/007804f3ff4d43dd4ac2137d254cc6e1112839c2/spec/models/conference_spec.rb#L1637
But yes works fine without it as well.

Comment (siddhantbajaj) [inline spec/models/conference_spec.rb]: > then there is already a conference variable at the top
But this is a already happened conference so I will have to change the start_date and end_date in the test so that I can successfully create my events. Therefore I didn't use it.

**Comment by Ana06** [comment]
@siddhantbajaj there is still one offense, maybe we can exclude this file from the Block cop, as we are excluding Conference class anyway from the line cop.

**Comment by siddhantbajaj** [comment]
done. :+1:
