### PR TITLE
Fixed flickering test

### LINKED ISSUE #1561: Flickering proposal feature test
This tests are sometimes failing:

```
Failures:
  1) Event as an conference organizer rejects a proposal
     Failure/Error: expect(flash).to eq('Event rejected!')
       
       expected: "Event rejected!"
            got: "none"
       
       (compared using ==)
     # ./spec/features/proposals_spec.rb:35:in `block (3 levels) in <top (required)>'
```

```
Failures:
  1) Event as an conference organizer accepts a proposal
     Failure/Error: expect(flash).to eq('Event accepted!')
       
       expected: "Event accepted!"
            got: "none"
       
       (compared using ==)
     # ./spec/features/proposals_spec.rb:46:in `block (3 levels) in <top (required)>'
```

```
  1) Event as an conference organizer restarts review of a proposal
     Failure/Error: expect(flash).to eq('Review started!')
       
       expected: "Review started!"
            got: "none"
       
       (compared using ==)
     # ./spec/features/proposals_spec.rb:59:in `block (3 levels) in <top (required)>'
  2) Event as an conference organizer accepts a proposal
     Failure/Error: expect(flash).to eq('Event accepted!')
       
       expected: "Event accepted!"
            got: "none"
       
       (compared using ==)
     # ./spec/features/proposals_spec.rb:46:in `block (3 levels) in <top (required)>'
```

### PR DESCRIPTION
**Pull request by siddhantbajaj**
Closes #1561 
Test were sometimes failing because of the delay between the click_link and the actual completion of the code that is run as a result of that click.
`page.has_content` always wait for the code to get completed and page to get reloaded.
We can also do `page.find(#flash).has_content` both works fine.

### CODE REVIEW

File: spec/features/proposals_spec.rb [hunk 1]
```diff
@@ -32,7 +32,7 @@
 
       click_button 'New'
       click_link "reject_event_#{@event.id}"
-      expect(flash).to eq('Event rejected!')
+      expect(page.has_content?('Event rejected!')).to be true
```
Comment (lagartoflojo) [inline spec/features/proposals_spec.rb]: Good catch! 
A nicer way of writing this is and the other fixes is:

```ruby
expect(page).to have_content 'Event rejected!'
```

File: spec/features/proposals_spec.rb [hunk 2]
```diff
@@ -43,7 +43,7 @@
 
       click_button 'New'
       click_link "accept_event_#{@event.id}"
-      expect(flash).to eq('Event accepted!')
+      expect(page.has_content?('Event accepted!')).to be true
       expect(page.has_content?('Unconfirmed')).to be true
```
Comment (lagartoflojo) [inline spec/features/proposals_spec.rb]: This line can also be improved :)

Comment (Ana06) [inline spec/features/proposals_spec.rb]: but unrelated to the PR :wink:

Comment (Ana06) [inline spec/features/proposals_spec.rb]: or add a new commit to refactor this, but not in the same one that it is used for fixing the flickering tests

Comment (lagartoflojo) [inline spec/features/proposals_spec.rb]: Sure, it can be another commit. But if someone is working on a file that would benefit from some unrelated cleaning, I think people should go for it (boyscout rule: Always leave the campground cleaner than you found it).

Comment (Ana06) [inline spec/features/proposals_spec.rb]: @lagartoflojo 
> Sure, it can be another commit. But if someone is working on a file that would benefit from some unrelated cleaning, I think people should go for it (boyscout rule: Always leave the campground cleaner than you found it).

I am not saying that this shouldn't be changed, just that should be in another commit, in favour of a clean git history :smile:

Comment (lagartoflojo) [inline spec/features/proposals_spec.rb]: Agreed! :)
