### PR TITLE
Fix user already subscribed exception

### LINKED ISSUE #1589: [production][subscriptions#create] ActiveRecord::RecordInvalid: Validation failed: User has already been taken, User already subscri...
subscriptions#create threw this 0 times
<pre>
ActiveRecord::RecordInvalid: Validation failed: User has already been taken, User already subscribed!
</pre>
[https://events.opensuse.org/conference/oS3DW/subscriptions](https://events.opensuse.org/conference/oS3DW/subscriptions)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca99dc71fa00b1000002/problems/596487efa8d5e5000cfd37a6)

### PR DESCRIPTION
**Pull request by dPliakos**
Rescue exception that is produced when user tries to subscribe in a conference that has already been subscribed to it.

Fixes #1589

### CODE REVIEW

**Comment by shlok007** [comment]
Hi @dPliakos !

I think we should try to reason why/where the exception is being raised and figure out a way to avoid the exception instead of rescuing it after it has been raised.

File: app/controllers/subscriptions_controller.rb [hunk 1]
```diff
@@ -10,6 +10,8 @@ def create
     else
       redirect_to root_path, error: subscription.errors.full_messages.to_sentence
     end
+  rescue ActiveRecord::RecordInvalid
```
Comment (differentreality) [inline app/controllers/subscriptions_controller.rb]: Instead of rescuing from the exception, we can avoid it all together. 
https://stackoverflow.com/a/27421738

File: app/controllers/subscriptions_controller.rb [hunk 2]
```diff
@@ -10,6 +10,8 @@ def create
...
+    redirect_to root_path, error: @subscription.errors.full_messages.to_sentence
   end
```
Comment (differentreality) [inline app/controllers/subscriptions_controller.rb]: Please post a screenshot of the error message being shown

Comment (dPliakos) [inline app/controllers/subscriptions_controller.rb]: I forgot it, sorry.
screenshot from 2017-07-15 23-56-27

**Comment by dPliakos** [comment]
@shlok007 Thank you for the suggestion!!

**Comment by dPliakos** [comment]
screenshot from 2017-07-15 23-56-27
screenshot from 2017-07-16 00-15-50

File: app/controllers/subscriptions_controller.rb [hunk 3]
```diff
@@ -5,21 +5,21 @@ class SubscriptionsController < ApplicationController
 
   def create
     @subscription = current_user.subscriptions.build(conference_id: @conference.id)
-    if @subscription.save!
+    save_succeed = @subscription.save
```
Comment (differentreality) [inline app/controllers/subscriptions_controller.rb]: Why do we need to save this in a variable?!

File: app/controllers/subscriptions_controller.rb [hunk 4]
```diff
@@ -5,19 +5,21 @@ class SubscriptionsController < ApplicationController
...
   end
 
   def destroy
     @subscription = current_user.subscriptions.find_by(conference_id: @conference.id)
-    if @subscription.destroy
+    if @subscription && @subscription.destroy
       redirect_to root_path, notice: "You have been unsubscribed and now you will not be receiving email notifications for #{@conference.short_title}."
     else
-      redirect_to root_path, error: @subscription.errors.full_messages.to_sentence
+      flash[:error] = 'You are not subscribed to that conference.'
```
Comment (differentreality) [inline app/controllers/subscriptions_controller.rb]: Why don't you add this in the beginning of the action so that we only go into destroy method when the user is subscribed? I would add the conference title to the error message as well.

**Comment by differentreality** [comment]
Your first screenshot shows 2 errors. I'd only expect to see one, sine the only error is that the user is already subscribed. Can you please investigate why we get 2?

File: app/controllers/subscriptions_controller.rb (hunk 3 above)
Comment (dPliakos) [inline app/controllers/subscriptions_controller.rb]: oops.. my bad...

File: app/controllers/subscriptions_controller.rb (hunk 4 above)
Comment (dPliakos) [inline app/controllers/subscriptions_controller.rb]: But what should happen if the destroy fail again even the subscription (if this is possible) ? 
if !@subscription
  # go to error
if @subscription.destoy
  # go to root_path
else 
  # does this else have to exist here?

Comment (differentreality) [inline app/controllers/subscriptions_controller.rb]: Yes, the second else is showing an error in case the destroy method fails. 

What you want to do is redirect to root_path with an error unless the subscription exists. 
You can do that in the beginning as you are showing, and then you can leave the destroy if-else as it is.

**Comment by dPliakos** [comment]
I see that `@subscription.errors.full_messages` is an array, so replacing the `to_sentence` function with the `full_messages.second` or `full_messages[2]` would make what we want (we also could make a for loop to find the error we want, if there is the possibility that this number might change in the future).

I could not find why exactly how @subscription get it's `errors:`, but I found that they have a relationship with `validates`. So maybe there is something like "inheritance" for errors while a resource is loaded. 

Second try to subscribe:
screenshot from 2017-07-16 19-22-18

Second try to unsubscribe:
screenshot from 2017-07-16 19-21-45

**Comment by differentreality** [comment]
@dPliakos can you be more specific as to which validation is related to our case? (With a file/line reference)

**Comment by dPliakos** [comment]
It seems like the validation we need is here: [app/models/subscriptions.rb, line 8](https://github.com/openSUSE/osem/blob/master/app/models/subscription.rb#L8)

But it seems `conference_id` is being validated again at line 2. 

So  if we remove that line, we will have the required error and  without any other consequences. Right ?

File: app/controllers/subscriptions_controller.rb [hunk 5]
```diff
@@ -5,19 +5,24 @@ class SubscriptionsController < ApplicationController
...
-      redirect_to root_path, error: subscription.errors.full_messages.to_sentence
+      redirect_to root_path, error: @subscription.errors.full_messages.to_sentence
     end
   end
 
   def destroy
     @subscription = current_user.subscriptions.find_by(conference_id: @conference.id)
-    if @subscription.destroy
+
+    if !@subscription
```
Comment (differentreality) [inline app/controllers/subscriptions_controller.rb]: You can extract this part into a standalone statement, so that it is not part of the if statement.
redirect_to ..., error: '...' unless @subscription

You can also redirect directly to root_path, that's the only place subscription comes from anyway.

**Comment by differentreality** [comment]
`User already subscribed!` message can become 'You are already subscribed to @conference.title' so that it is similar to other messages. 
Please use conference.title instead of short_title in messages.

File: app/controllers/subscriptions_controller.rb [hunk 6]
```diff
@@ -5,19 +5,21 @@ class SubscriptionsController < ApplicationController
...
 
   def destroy
     @subscription = current_user.subscriptions.find_by(conference_id: @conference.id)
+
+    redirect_to root_path, error: "You are not subscribed to #{@conference.short_title}." and return unless @subscription
     if @subscription.destroy
       redirect_to root_path, notice: "You have been unsubscribed and now you will not be receiving email notifications for #{@conference.short_title}."
     else
-      redirect_to root_path, error: @subscription.errors.full_messages.to_sentence
+      redirect_to  root_path, error: "You are not subscribed to #{@conference.short_title}."
```
Comment (differentreality) [inline app/controllers/subscriptions_controller.rb]: Remove the extra space here

File: app/models/subscription.rb [hunk 7]
```diff
@@ -1,5 +1,5 @@
 class Subscription < ActiveRecord::Base
-  validates :user_id, uniqueness: { scope: [:conference_id] }
+
```
Comment (differentreality) [inline app/models/subscription.rb]: remove empty line

File: app/controllers/subscriptions_controller.rb [hunk 8]
```diff
@@ -5,19 +5,21 @@ class SubscriptionsController < ApplicationController
 
   def create
     @subscription = current_user.subscriptions.build(conference_id: @conference.id)
-    if @subscription.save!
+    if @subscription.save
       redirect_to root_path, notice: "You have been subscribed to receive email notifications for #{@conference.short_title}."
```
Comment (differentreality) [inline app/controllers/subscriptions_controller.rb]: BTW why don't we also fix this message: You have subscribed.... for @conference.title

File: app/controllers/subscriptions_controller.rb [hunk 9]
```diff
@@ -5,19 +5,21 @@ class SubscriptionsController < ApplicationController
...
     else
-      redirect_to root_path, error: subscription.errors.full_messages.to_sentence
+      redirect_to root_path, error: @subscription.errors.full_messages.to_sentence
     end
   end
 
   def destroy
     @subscription = current_user.subscriptions.find_by(conference_id: @conference.id)
+
+    redirect_to root_path, error: "You are not subscribed to #{@conference.short_title}." and return unless @subscription
```
Comment (differentreality) [inline app/controllers/subscriptions_controller.rb]: empty line after this one

Comment (differentreality) [inline app/controllers/subscriptions_controller.rb]: @conference.title instead of short_title

Comment (differentreality) [inline app/controllers/subscriptions_controller.rb]: If you use parenthesis for redirect, you can do `&& return`, and make rubocop happy! Let me know if you understand why this happens.

File: app/controllers/subscriptions_controller.rb [hunk 10]
```diff
@@ -5,19 +5,21 @@ class SubscriptionsController < ApplicationController
...
     if @subscription.destroy
       redirect_to root_path, notice: "You have been unsubscribed and now you will not be receiving email notifications for #{@conference.short_title}."
     else
-      redirect_to root_path, error: @subscription.errors.full_messages.to_sentence
+      redirect_to root_path, error: "You are not subscribed to #{@conference.short_title}."
```
Comment (differentreality) [inline app/controllers/subscriptions_controller.rb]: This error message was for our case in line 18, the error message here, in case @subscription.destroy fails should remain the same.

Comment (dPliakos) [inline app/controllers/subscriptions_controller.rb]: So we delete this error and leave the redirect_to as is, or delete both ?

Comment (differentreality) [inline app/controllers/subscriptions_controller.rb]: Take a moment to think what makes sense, what we are doing here, and why, and let me know what _you_ propose we should do :)

**Comment by differentreality** [comment]
@dPliakos ping

File: app/controllers/subscriptions_controller.rb [hunk 11]
```diff
@@ -5,19 +5,21 @@ class SubscriptionsController < ApplicationController
...
     else
-      redirect_to root_path, error: subscription.errors.full_messages.to_sentence
+      redirect_to root_path, error: @subscription.errors.full_messages.to_sentence
     end
   end
 
   def destroy
     @subscription = current_user.subscriptions.find_by(conference_id: @conference.id)
+
+    (redirect_to root_path, error: "You are not subscribed to #{@conference.title}.") && return unless @subscription
```
Comment (differentreality) [inline app/controllers/subscriptions_controller.rb]: Why do you need parenthesis at the beginning of the line instead of after redirect_to
`redirect(path, error: ...)`

File: app/controllers/subscriptions_controller.rb [hunk 12]
```diff
@@ -5,19 +5,21 @@ class SubscriptionsController < ApplicationController
...
     if @subscription.destroy
-      redirect_to root_path, notice: "You have been unsubscribed and now you will not be receiving email notifications for #{@conference.short_title}."
+      redirect_to root_path, notice: "You have been unsubscribed and now you will not be receiving email notifications for #{@conference.title}."
```
Comment (differentreality) [inline app/controllers/subscriptions_controller.rb]: Lose the `been` here as well.

File: app/controllers/subscriptions_controller.rb [hunk 13]
```diff
@@ -5,19 +5,21 @@ class SubscriptionsController < ApplicationController
...
     else
-      redirect_to root_path, error: @subscription.errors.full_messages.to_sentence
+      redirect_to root_path, error: "You are not subscribed to #{@conference.title}."
```
Comment (differentreality) [inline app/controllers/subscriptions_controller.rb]: But you showed that error message already, and if the user is not subscribed, will never reach this section of the code! What's confusing you here?

Comment (dPliakos) [inline app/controllers/subscriptions_controller.rb]: What happens if the destroy fails, even if the subscription exists. Is it possible in the first place ?

File: app/controllers/subscriptions_controller.rb (hunk 11 above)
Comment (dPliakos) [inline app/controllers/subscriptions_controller.rb]: Miss-understood the syntax. it' s clear now.

File: app/controllers/subscriptions_controller.rb (hunk 13 above)
Comment (differentreality) [inline app/controllers/subscriptions_controller.rb]: We have a subscription, we try to destroy it, that doesn't work for some reason.
We still have a subscription. And we show the error message. I still don't understand why you are trying to change this line in the first place.

Comment (dPliakos) [inline app/controllers/subscriptions_controller.rb]: The message says that there is not such a subscription. But there is (and it fails to be destroyed).

Comment (differentreality) [inline app/controllers/subscriptions_controller.rb]: How can I reproduce this on my machine?

Comment (dPliakos) [inline app/controllers/subscriptions_controller.rb]: I do not know if it possible for such an error to exist :p

Comment (differentreality) [inline app/controllers/subscriptions_controller.rb]: @dPliakos you just said that the error says there is no such subscription. Well, how do you know that if you can't see the error message?! I really don't understand your point. Please be clear, so that we can finish this.

Comment (dPliakos) [inline app/controllers/subscriptions_controller.rb]: def destroy:
  check if there is the subscription.
  if no: go back with an error
  if yes: destroy it
  //   question: Is there the possibility that this destroy() function may fail for other reason than the absence of subscription ?

Comment (differentreality) [inline app/controllers/subscriptions_controller.rb]: Possibly. If it does, it can show the message(s) that made it fail. What's wrong with that?

Comment (dPliakos) [inline app/controllers/subscriptions_controller.rb]: What message to put there? :D XD

File: app/controllers/subscriptions_controller.rb (hunk 12 above)
Comment (dPliakos) [inline app/controllers/subscriptions_controller.rb]: done

File: app/controllers/subscriptions_controller.rb (hunk 11 above)
Comment (dPliakos) [inline app/controllers/subscriptions_controller.rb]: produces syntax error.

Comment (dPliakos) [inline app/controllers/subscriptions_controller.rb]: It as my bad syntax. Fixed.

**Comment by differentreality** [comment]
@dPliakos do you see the failing tests? Please fix them too!!

**Comment by dPliakos** [comment]
finally :D

**Comment by differentreality** [comment]
:+1:  Nice work @dPliakos :tada:
